### ISSUE TITLE
missing libudev on raspbian?

### ISSUE THREAD

**Issue by pelikhan** [node-usb/node-usb#480]
It seems that libudev-dev is not installed by default on raspbian; as a result, node-usb fails to install.

```
make: Entering directory '/home/pi/gh/jacdac-cli/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
../libusb/libusb/os/linux_udev.c:40:10: fatal error: libudev.h: No such file or directory
   40 | #include <libudev.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [libusb.target.mk:154: Release/obj.target/libusb/libusb/libusb/os/linux_udev.o] Error 1
make: Leaving directory '/home/pi/gh/jacdac-cli/node_modules/usb/build'
```

I installed it manually and run the install again and things worked. 
```
sudo apt install libudev-dev
```

I wonder if this kind of dependencies can be baked into the package.json.

**Comment by thegecko** [comment]
`libudev-dev` is a compilation requirement which would be difficult to include.

I'm more concerned why the prebuilt binaries don't work (RPi should use the arm-linux prebuilds)

**Comment by thegecko** [comment]
I've just tested `v2.1.2` on rpi and rpi64 with no issue. They use the shipped prebuild binaries.

There should be no need to compile the package, are you trying to rebuild the package with `electron-rebuild` or similar?

**Comment by pelikhan** [comment]
I was doing a yarn install on my package that uses usb v2.1.2.

I did run apt update/upgrade before that. Maybe I need a new image.
________________________________

**Comment by thegecko** [comment]
TBF, this is all testing via a remote CLI, but I doubt running it through raspbian should make a difference.

**Comment by mildsunrise** [comment]
This issue should be closed, as libudev should never be bundled statically AFAIK.
Instead we should add instructions to the README telling users to install `build-essential libudev-dev` if the prebuilds don't work.

And yes it is normal for prebuilds not to work, especially on Raspis and other embedded devices, because of libc compatibility issues:

~~~
Error: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/user/app/node_modules/usb/prebuilds/linux-arm64/node.napi.armv8.node)
~~~

In that case it will fall back to compilation and you'll need libudev-dev.
If I find time, I'll try to make prebuilds target an older glibc version to make them more portable.

**Comment by thegecko** [comment]
I'll close this issue as I agree libudev-dev is an end user concern.

@mildsunrise , if you want to look at the prebuild images, they are maintained here:

https://github.com/node-usb/docker-images

**Comment by pelikhan** [comment]
A little note in the readme would be awesome! Thanks for digging into this.
________________________________
