### ISSUE TITLE
printer cannot be used by other app

### ISSUE THREAD

**Issue by dadinugroho** [node-usb/node-usb#502]
Hi All, 

I have a case where I wanted to use https://github.com/ThinhVu/tsc-printer-js. This require to use this package. then, I need to run zadig to install winusb driver. This works perfect, until I wanted to use my printer with other label software. My printer is not detected. 

How can I still use the printer after I used zadig to installed winusb driver.

**Comment by noah-moutfitters** [comment]
@dadinugroho Speaking from personal experience, you may fail at this. Do you know what your original driver was?

**Comment by mildsunrise** [comment]
I don't use Windows so correct me if wrong, but... it only allows one driver to handle a USB device, right? If instead of your normal driver you set it to use Zadig, then 'normal' applications can't use it since it doesn't appear as a printer. You'll have to install the original driver back for that. 

To my knowledge, Windows is the only OS with this limitation. Linux, Macos, etc should be fine.

@thegecko we keep getting these questions, maybe we should add a disclaimer to the README?

**Comment by thegecko** [comment]
Yeah, this is a libusb on Windows usage issue really. If your device doesn't have a winusb driver you need to use zadig or the usbdk backend and both approaches claim exclusive access AFAICT

**Comment by mildsunrise** [comment]
> If your device doesn't have a winusb driver

Ah okay, that was the part I was missing. So it depends on support from the original driver, I see.

**Comment by dadinugroho** [comment]
Thank you @mildsunrise @thegecko . I would just want to confirm that. In my situation, it is a bit difficult and impractical should I need to keep changing the driver. 

The other issue with using zadig is that it cannot rolled back the old driver. I need to install the driver again from the beginning. Or, it is just me that does not know how to revert back the driver easily?

It is true I am using windows in my client side. Maybe I should setup a print server using linux and attached the printer and not keep changing the driver.

**Comment by mildsunrise** [comment]
I don't know much about Windows but again, if it's a Linux box then it should work :)
