### ISSUE TITLE
Windows 7 support?

### ISSUE THREAD

**Issue by chsing** [node-usb/node-usb#547]
Not so much a bug report as a question for clarification: does this package support Windows 7? I saw in [this PR](https://github.com/node-usb/node-usb/pull/524) comments about Windows 7 not being supported, but can't find any documentation anywhere that confirms this, so just wanted to get a confirmation.

Asking because I'm getting this error when trying to run my Electron app on Windows 7:
![image](https://user-images.githubusercontent.com/4857700/191809348-297d3a77-2f42-4f76-a434-c1a2948c7d52.png)

It runs fine on Windows 10.

Thanks!

## Additional Information
- Operating System: Windows 7
- Runtime: node v16.14.2, Electron v19.0.0
- Node USB Version: v2.5.1

**Comment by thegecko** [comment]
Hmm,

There's a prebuilt binary for win32 created here:

https://github.com/node-usb/node-usb/blob/master/.github/workflows/prebuild.yml#L23

It uses the oldest windows runner available, but I don't have access to any Windows 7 machines to test. It should work in theory, but your issue suggests it doesn't.

Feel free to determine the issue otherwise I'm not sure we will get any traction from others to fix this :/

**Comment by chsing** [comment]
Okay, thanks for the info!
